// Stage 2 - Zolve/react-app/src/App.jsx
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { useState, useEffect } from 'react';
import Landing from './pages/Landing';
import Login from './pages/auth/Login';
import Signup from './pages/auth/Signup';
import Dashboard from './pages/Dashboard';
import Tickets from './pages/Tickets';
import { isAuthenticated, logout } from './utils/auth';
import toast from 'react-hot-toast';
import { Link } from 'react-router-dom';

function ProtectedRoute({ children }) {
  if (!isAuthenticated()) {
    toast.error('Your session has expired — please log in again.');
    return <Navigate to="/auth/login" />;
  }
  return children;
}

function Navbar() {
  const [auth, setAuth] = useState(isAuthenticated());
  const [menuOpen, setMenuOpen] = useState(false); // For hamburger

  useEffect(() => {
    const checkAuth = () => setAuth(isAuthenticated());
    window.addEventListener('storage', checkAuth);
    return () => window.removeEventListener('storage', checkAuth);
  }, []);

  const handleLogout = () => {
    logout();
    setAuth(false);
    toast.success('Logged out successfully');
  };

  return (
    <header style={{ background: '#1f2937', color: 'white', padding: '1rem' }}>
      <div className="container" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Link to="/"><h2>Zolve</h2></Link>
        <div className="hamburger" onClick={() => setMenuOpen(!menuOpen)}>
          <div></div>
          <div></div>
          <div></div>
        </div>
        <nav className={`nav-menu ${menuOpen ? 'open' : ''}`}>
          {auth ? (
            <>
              <Link to="/dashboard" className="nav-link" onClick={() => setMenuOpen(false)}>Dashboard</Link>
              <Link to="/tickets" className="nav-link" onClick={() => setMenuOpen(false)}>Tickets</Link>
              <button onClick={() => { handleLogout(); setMenuOpen(false); }} className="btn btn-danger">Logout</button>
            </>
          ) : (
            <>
              <Link to="/auth/login" className="nav-link" onClick={() => setMenuOpen(false)}>Login</Link>
              <Link to="/auth/signup" className="nav-link" onClick={() => setMenuOpen(false)}>Signup</Link>
            </>
          )}
        </nav>
      </div>
    </header>
  );
}

export default function App() {
  return (
    <BrowserRouter>
      <Navbar />
      <Routes>
        <Route path="/" element={<Landing />} />
        <Route path="/auth/login" element={<Login />} />
        <Route path="/auth/signup" element={<Signup />} />
        <Route path="/dashboard" element={<ProtectedRoute><Dashboard /></ProtectedRoute>} />
        <Route path="/tickets" element={<ProtectedRoute><Tickets /></ProtectedRoute>} />
      </Routes>
    </BrowserRouter>
  );
}

// Stage 2 - Zolve/vue-app/src/App.vue
<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { isAuthenticated, logout } from './utils/auth'
import { useToast } from 'vue-toastification'

const toast = useToast()
const router = useRouter()
const auth = ref(isAuthenticated())
const menuOpen = ref(false)

const handleLogout = () => {
  logout()
  auth.value = false
  toast.success('Logged out successfully')
  router.push('/')
  menuOpen.value = false
}

onMounted(() => {
  const handleAuthChange = () => {
    auth.value = isAuthenticated()
  }
  window.addEventListener('authChange', handleAuthChange)
  window.addEventListener('storage', handleAuthChange)
})
</script>

<template>
  <header style="background: #1f2937; color: white; padding: 1rem;">
    <div class="container" style="display: flex; justify-content: space-between; align-items: center;">
      <router-link to="/"><h2>Zolve</h2></router-link>
      <div class="hamburger" @click="menuOpen = !menuOpen">
        <div></div>
        <div></div>
        <div></div>
      </div>
      <nav :class="['nav-menu', { open: menuOpen }]">
        <template v-if="auth">
          <router-link to="/dashboard" class="nav-link" @click="menuOpen = false">Dashboard</router-link>
          <router-link to="/tickets" class="nav-link" @click="menuOpen = false">Tickets</router-link>
          <button @click="handleLogout" class="btn btn-danger">Logout</button>
        </template>
        <template v-else>
          <router-link to="/auth/login" class="nav-link" @click="menuOpen = false">Login</router-link>
          <router-link to="/auth/signup" class="nav-link" @click="menuOpen = false">Signup</router-link>
        </template>
      </nav>
    </div>
  </header>
  <router-view></router-view>
</template>
